specific_random_elements:
  hairstyles:
    # - length: "Short Hair"
    #   style:
    #     - "Bowl Cut Hair"
    #     - "Bob Cut"
    #     - "Gracie Abrams Bob"
    #     - "Rounded Bob"
    #     - "Bob With Bangs"
    #     - "French Bob"
    #     - "Pixie Cut"
    #     - "Curtain Bangs"
    #     - "Side-Swept Bangs"
    #     - "Shag Cut"
    - length: "Medium Hair"
      style:
        # - "Bob Cut"
        - "Lower Ponytail"
        - "High Ponytail"
        # - "Long Bob"
        # - "Face-Framing Layers"
        - "Side Part"
        - "Curtian Bangs"
        - "Shag Cut with Modern Layers"
        - "Modern Mullet"
        - "Bangs with Layers"
        - "Jane Birkin Bangs"
        - "Bombshell Bangs"
    - length: "Long Hair"
      style:
        - "Lower Ponytail"
        - "High Ponytail"
        - "Layered Cut"
        - "Face-Framing Layers"
        - "Side Part"
        - "Bangs with Layers"
        - "Curtain Bangs"
        - "Half-Up Half-Down"
        - "Laminated Ponytail"
        - "Fairy Waves Style"
    - length: "Very Long Hair"
      style:
        - "Lower Ponytail"
        - "High Ponytail"
        - "Mermaid Waves"
        - "Fairy Waves"
        - "Face-Framing Layers"
        - "Curtain Bangs"
        - "Bohemian Layers"

  hairqualities:
    - "Straight Hair"
    - "Shiny Hair"
    - "Perm Hair"
    - "Wavy Hair"
    - "Curly Hair"
    - "High Shine Hair"
    - "Triple Barrel Waves"
    - "Hydrated Bouncy Curls"
    - "Beachy Waves"
    - "Glass Hair"
    - "Silky Smooth"
    - "Fluffy Volume"
    - "Feathered Texture"
    - "Tousled Texture"
    - "Sleek Laminated Look"

  haircolors:
    - "deep black hair with blue sheen"
    - "rich mahogany brown hair"
    - "mocha brown hair with caramel highlights"
    - "chocolate brown hair with rich dimension"
    - "honey brown hair with golden highlights"
    - "ash blonde hair with cool undertones"
    - "strawberry blonde hair with rosy tint"
    - "jet black hair with intense shine"

  cloths:
    - "(Bikini:1.2)"
    - "(micro bikini:1.2)"
    - "(low rise bikini:1.2)"
    - "(side-tie bikini:1.2)"
    - "(Fringe bikini:1.2)"
    - "(babydoll:1.2)"
    - "(body Strap Lingerie:1.2)"
    - "(bra and Garter Belt Set:1.2)"
    - "(bralette:1.2)"
    - "(feather Lingerie Set:1.2)"
    - "(seductive lingerie:1.2)"
    - "(see through lingerie:1.2)"
    - "(calvin Klein underwear:1.2)"
    - "(sports Bra,:1.2)"
    - "(plunge Bra,:1.2)"
    - "(bikini Panties,:1.2)"
    - "(brazilian Panties,:1.2)"
    - "(seamless Panties,:1.2)"
    - "(tap Pants,:1.2)"
    - "(tanga Panties,:1.2)"
    - "(mesh Panties,:1.2)"
    - "(strapless Slip,:1.2)"
    - "(bodycon Slip,:1.2)"
    - "(glamorous camisole:1.2)"
    - "(lace Camisole,:1.2)"
    - "(mesh Camisole,:1.2)"
    - "(cropped Camisole,:1.2)"
    - "(cut Out Camisole,:1.2)"
    - "(no bra plunging necklines shirts:1.2)"
    - "(feather Boa:1.2)"
    - "(bodystocking:1.2)"
    - "(fishnet Bodystocking:1.2)"
    - "(fringe Bodystocking:1.2)"
    - "(plunging necklines bathrobe:1.2)"
    - "(bodycon mini Dress:1.2)"
    - "(corset with Garter Straps:1.2)"
    - "(Sheer Lace Teddy:1.2)"
    - "(strappy Harness Bra:1.2)"
    - "(cupless Bra with Chains:1.2)"
    - "(crotchless Panties:1.2)"
    - "(vinyl Lingerie Set:1.2)"
    - "(leather Harness Outfit:1.2)"
    - "(fishnet Dress:1.2)"
    - "(backless Bodysuit:1.2)"
    - "(sheer Negligee:1.2)"
    - "(peek-a-boo Bra:1.2)"
    - "(adjustable Strap Lingerie:1.2)"
    - "(metallic Bikini:1.2)"
    - "(latex Catsuit:1.2)"
    - "(keyhole Monokini:1.2)"
    - "(cage Bra:1.2)"
    - "(extreme Micro Bikini:1.2)"
    - "(bodychain Lingerie:1.2)"
    - "(barely There Bikini:1.2)"
    - "(sheer Babydoll:1.2)"
    - "(strappy Bodysuit:1.2)"
    - "(cupless Corset:1.2)"
    - "(rope Harness:1.2)"
    - "(keather Bikini:1.2)"
    - "(transparent Bodysuit:1.2)"
    - "(bondage Inspired Lingerie:1.2)"
    - "(wet Look Lingerie:1.2)"
    - "(sequin Bikini:1.2)"
    - "(barely Covering Top:1.2)"
    - "(extreme Low Rise Panties:1.2)"
    - "(sheer Mesh Bodysuit:1.2)"
    - "(barely There Bra:1.2)"
    - "(extreme Plunge Bodysuit:1.2)"
    - "(strappy Monokini:1.2)"
    - "(sheer Lace Bodysuit:1.2)"
    - "(extreme Backless Dress:1.2)"
    - "(barely Covering Lingerie:1.2)"
    - "(sheer Mesh Dress:1.2)"
    - "(extreme Sideboob Top:1.2)"
    - "(barely There Panties:1.2)"
    - "(extreme Cleavage Dress:1.2)"
    - "(barely Covering Swimwear:1.2)"
    - "(sheer Silk Negligee:1.2)"
    - "(towel draped over naked body:1.2)"
    - "(white shirt only:1.2)"
    - "(apron only:1.2)"

  # general_random_elementsから移動
  facial_features:
    - "BREAK (seductive smile half-open mouth:1.2)"
    - "BREAK (bedroom eyes sultry gaze:1.2)"
    - "BREAK (biting lip alluring expression:1.2)"
    - "BREAK (naughty grin mischievous smile:1.2)"
    - "BREAK (smirk confident and sexy:1.2)"
    - "BREAK (tongue out playful expression:1.2)"
    - "BREAK (intense eye contact seductive stare:1.2)"
    - "BREAK (inviting gaze with lowered eyelashes:1.2)"
    - "BREAK (sultry half-closed eyes dreamy look:1.2)"
    - "BREAK (playful wink with coy smile:1.2)"
    - "BREAK (passionate gaze with parted lips:1.2)"
    - "BREAK (gentle bite on lower lip:1.2)"
    - "BREAK (teasing smile with raised eyebrow:1.2)"
    - "BREAK (confident smirk with direct gaze:1.2)"
    - "BREAK (alluring pout with glossy lips:1.2)"
    - "BREAK (enchanting smile with sparkling eyes:1.2)"
    - "BREAK (come-hither look with beckoning eyes:1.2)"
    - "BREAK (sensual expression with half-open mouth:1.2)"
    - "BREAK (captivating stare with magnetic appeal:1.2)"
    - "BREAK (playful tongue peek with mischief:1.2)"
    - "BREAK (passionate intensity with burning gaze:1.2)"
    - "BREAK (irresistible charm with captivating smile:1.2)"
    - "BREAK (sultry elegance with refined beauty:1.2)"
    - "BREAK (mesmerizing appeal with hypnotic beauty:1.2)"

  expressions:
    # 既存のexpressionsも移動（コメントアウト済みでも構造は維持）

  breast_size:
    - "BREAK (natural big Breasts, Non-plastic breast:1.4), (erection of small round nipple:1.4), (cleavage:1.4), (small areolas:1.4)"
    - "BREAK (natural mega Breasts, Non-plastic breast:1.4), (erection of small round nipple:1.4), (cleavage:1.4), (small areolas:1.4)"
    # - "BREAK (natural large Breasts, Non-plastic breast:1.4), (erection of small nipple:1.4), (cleavage:1.4)"
    - "BREAK (natural huge Breasts, Non-plastic breast:1.4), (erection of small round nipple:1.4), (cleavage:1.4), (small areolas:1.4)"

  Sexual_expressions:
    # - "BREAK (erection of nipple:1.4)"
    # - "BREAK (cleavage:1.4)"
    - "BREAK (breasts apart:1.4)"
    - "BREAK (breast press:1.4)"
    - "BREAK (breast hold:1.4)"
    - "BREAK (sagging breasts:1.4)"
    - "BREAK (bursting breasts:1.4)"
    - "BREAK (hanging breasts:1.4)"
    - "BREAK (perky breasts:1.4)"
    - "BREAK (pointy breasts :1.4)"
    - "BREAK (veiny breasts :1.4)"
    - "BREAK (underboob:1.4)"
    - "BREAK (sideboob:1.4)"
    - "BREAK (cleft of venus:1.4)"

  background:
    - "BREAK (luxury hotel suite bedroom, king size bed, soft romantic lighting, city skyline view through floor-to-ceiling windows, intimate atmosphere:1.3)"
    - "BREAK (five-star hotel presidential suite, marble bathroom with jacuzzi, champagne on table, dim candlelight, elegant décor:1.3)"
    - "BREAK (boutique hotel room with fireplace, cozy atmosphere, wine glasses on side table, soft warm lighting:1.3)"
    - "BREAK (bedroom with double bed, silk sheets, rose petals scattered, soft romantic lighting, private intimate atmosphere:1.3)"
    - "BREAK (master bedroom with panoramic windows, city lights view, modern minimalist design, king size bed:1.3)"
    - "BREAK (rooftop terrace penthouse, city skyline at night, outdoor furniture, starry sky, intimate urban setting:1.3)"
    - "BREAK (luxury yacht cabin interior, ocean view through portholes, elegant maritime décor, intimate sailing experience:1.3)"
    - "BREAK (penthouse apartment living room, floor-to-ceiling windows, luxury furniture, champagne service, exclusive atmosphere:1.3)"
    - "BREAK (private spa suite with massage table, essential oils, soft music, relaxing couples treatment room:1.3)"
    - "BREAK (luxury car interior during night drive, leather seats, city lights passing by, intimate road trip moment:1.3)"
    - "BREAK (modern art gallery with white walls, dramatic lighting, contemporary sculptures, sophisticated cultural setting:1.3)"
    - "BREAK (executive office with glass walls, city view, modern furniture, professional power setting:1.3)"
    - "BREAK (moonlit beach with soft waves, silvery sand, starry sky, romantic seaside atmosphere:1.3)"
    - "BREAK (vintage photography studio with film lights, classic equipment, artistic atmosphere, creative professional space:1.3)"
    - "BREAK (rooftop garden with city skyline, green plants, urban oasis, peaceful elevated sanctuary:1.3)"
    - "BREAK (designer loft apartment with exposed brick, industrial chic, modern art, trendy urban living:1.3)"
    - "BREAK (private members club with leather furniture, fireplace, exclusive atmosphere, elite social setting:1.3)"
    - "BREAK (penthouse balcony with infinity pool, city panorama, luxury outdoor living, exclusive urban retreat:1.3)"
    - "BREAK (luxury train compartment with vintage elegance, velvet seats, romantic journey, nostalgic travel experience:1.3)"
    - "BREAK (minimalist zen garden with water features, stone paths, peaceful meditation, tranquil Japanese aesthetics:1.3)"
    - "BREAK (secret speakeasy with dim lighting, vintage cocktails, prohibition era atmosphere, hidden underground venue:1.3)"
    - "BREAK (luxury desert oasis with palm trees, clear water, exotic atmosphere, romantic Middle Eastern setting:1.3)"
    - "BREAK (opulent ballroom with crystal chandeliers, marble floors, grand architecture, aristocratic elegance:1.3)"
    - "BREAK (private vineyard with rolling hills, grape vines, romantic countryside, wine country elegance:1.3)"
    - "BREAK (luxury shopping district with designer stores, elegant architecture, upscale commercial atmosphere:1.3)"
    - "BREAK (sakura grove in full bloom, pink petals falling, Japanese spring, romantic cherry blossom setting:1.3)"
    - "BREAK (sacred hot spring with mineral deposits, natural therapy, healing waters, spiritual cleansing sanctuary:1.3)"

  # 新規追加：セクシー系グラビアポーズ50個
  poses:
    - "BREAK (seductive arched back pose with hands on hips:1.3)"
    - "BREAK (sultry over-the-shoulder glance pose:1.3)"
    - "BREAK (provocative leaning forward pose with cleavage emphasis:1.3)"
    - "BREAK (sensual hands-through-hair pose with eyes closed:1.3)"
    - "BREAK (glamorous pin-up pose with one leg raised:1.3)"
    - "BREAK (teasing peek-a-boo pose behind sheer fabric:1.3)"
    - "BREAK (confident power pose with hands on waist:1.3)"
    - "BREAK (playful sitting pose with legs crossed seductively:1.3)"
    - "BREAK (intimate mirror reflection pose:1.3)"
    - "BREAK (dramatic silhouette pose against window:1.3)"
    - "BREAK (sensual stretching pose with arms raised:1.3)"
    - "BREAK (provocative bending over pose:1.3)"
    - "BREAK (alluring lying down pose with one knee up:1.3)"
    - "BREAK (seductive crawling pose on all fours:1.3)"
    - "BREAK (glamorous standing pose with hip thrust:1.3)"
    - "BREAK (sultry sitting on edge pose:1.3)"
    - "BREAK (teasing undressing pose with clothing partially removed:1.3)"
    - "BREAK (sensual bathtub pose with water cascading:1.3)"
    - "BREAK (provocative kneeling pose with back arched:1.3)"
    - "BREAK (alluring dance pose with flowing movement:1.3)"
    - "BREAK (seductive bed pose with sheets artfully draped:1.3)"
    - "BREAK (glamorous vintage pin-up pose:1.3)"
    - "BREAK (sultry yoga pose with flexibility showcased:1.3)"
    - "BREAK (teasing upside-down pose with hair cascading:1.3)"
    - "BREAK (sensual embrace pose with invisible partner:1.3)"
    - "BREAK (provocative squatting pose with powerful stance:1.3)"
    - "BREAK (alluring twisting pose showing curves:1.3)"
    - "BREAK (seductive reclining pose on luxury furniture:1.3)"
    - "BREAK (glamorous staircase pose with dramatic lighting:1.3)"
    - "BREAK (sultry shower pose with water droplets:1.3)"
    - "BREAK (teasing peek through doorway pose:1.3)"
    - "BREAK (sensual floor pose with legs elegantly positioned:1.3)"
    - "BREAK (provocative wall-leaning pose with body pressed against surface:1.3)"
    - "BREAK (alluring balcony pose with wind-blown hair:1.3)"
    - "BREAK (seductive poolside pose with wet look:1.3)"
    - "BREAK (glamorous car hood pose with confident attitude:1.3)"
    - "BREAK (sultry beach pose with sand and waves:1.3)"
    - "BREAK (teasing between-sheets pose in bed:1.3)"
    - "BREAK (sensual champagne celebration pose:1.3)"
    - "BREAK (provocative high-heel emphasis pose:1.3)"
    - "BREAK (alluring window-sill sitting pose:1.3)"
    - "BREAK (seductive rope or chain artistic pose:1.3)"
    - "BREAK (glamorous red carpet style pose:1.3)"
    - "BREAK (sultry candlelit romantic pose:1.3)"
    - "BREAK (teasing silky fabric play pose:1.3)"
    - "BREAK (sensual morning-in-bed awakening pose:1.3)"
    - "BREAK (alluring submissive vulnerable pose:1.3)"

# general_random_elementsは空に（全要素をspecific_random_elementsに移動済み）
general_random_elements: {}
